### ISSUE TITLE
Any tips on how to run on a card with 11gb VRAM

### ISSUE THREAD

**Issue by Kvento** [kijai/ComfyUI-PyramidFlowWrapper#13]
I'm trying to run the model on my RTX 2080ti, but so far I haven't been able to succeed. 

The video memory consumption is too high and when running with the standard workflow settings (loading the model on **bf16**) I get a crash and the message "Allocation on device". 
But if I enable the **fp16** mode and model **dtype fp8_e4m3fn** then the model loads without crashes, but during the execution of the **PyramidFlow Sampler** block, the memory consumption is just crazy. This goes beyond the video card memory and Shared GPU Memory starts working and the processing time tends to infinity.

I read that others run the model with less memory consumption, so I think maybe I'm doing something wrong?
I have already deleted and re-downloaded ComfyUI portable and the required nodes, but the result has not changed.

![2024-10-11_21-22-38](https://github.com/user-attachments/assets/174d7596-01b2-4666-8fc1-665863800f2f)
![2024-10-11_21-09-58](https://github.com/user-attachments/assets/703c6046-e7c9-4242-8f19-88c1012deefe)

**Comment by kijai** [comment]
It's very close to what it needs, maybe you have some other software take up VRAM in Windows? With my large monitor and having browser up with many tabs etc. Windows can take 1-3GB VRAM on it's own.

**Comment by Kvento** [comment]
No, my standard system video memory consumption is 0.6 - 0.9Gb, so before launching ComfyUI I close any software or utilities that can affect video memory consumption.

![2024-10-11_22-47-05](https://github.com/user-attachments/assets/a1d71572-e4a1-4e4a-baa0-ba2a10d08c06)

**Comment by kijai** [comment]
That's odd then, with fp8 it's not even taking 10GB for me... I'm on torch 2.4.1 cu124, not sure what else could affect it.

**Comment by rixjsjsbxh** [comment]
“2080ti doesn’t support BF16, so I can only use FP16, but FP16 throws NaN errors. I tried running it with FP8, but the memory usage is outrageous. Even with 22GB of VRAM, it still runs out of memory.”
![Uploading a805673598f147b74e6d7c3bd8fc8702.png…]()

**Comment by rixjsjsbxh** [comment]
![Uploading a805673598f147b74e6d7c3bd8fc8702.png…]()

**Comment by rixjsjsbxh** [comment]
![Uploading a805673598f147b74e6d7c3bd8fc8702.jp
![a805673598f147b74e6d7c3bd8fc8702](https://github.com/user-attachments/assets/3fc31fbc-64e8-4670-a3af-9ee514c21566)
eg…]()

**Comment by rixjsjsbxh** [comment]
![a805673598f147b74e6d7c3bd8fc8702](https://github.com/user-attachments/assets/efa45572-ea74-472f-b492-785a8e94a165)
![a805673598f147b74e6d7c3bd8fc8702](https://github.com/user-attachments/assets/08a31975-f274-4db0-b0bb-58f5cad5bca5)

**Comment by Kvento** [comment]
> “2080ti doesn’t support BF16, so I can only use FP16, but FP16 throws NaN errors. I tried running it with FP8, but the memory usage is outrageous. Even with 22GB of VRAM, it still runs out of memory.”

Yeah the same. If I run in fp16 I get the error "nan in latents" in the "PyramidFlow Sampler" block, and with fp8 the memory consumption is simply outrageous.

I'm not sure if "CPU offloading" is implemented in these nodes (I just couldn't find any setting with a similar name), but by analogy with CogVideoX, it could help launch the model on video cards with a smaller amount of VRAM.
Although CogVideoX also didn't launch for me without "CPU offloading" enabled on the standard model. But the GGUF version launched without "CPU offloading" enabled.

I hope that @kijai will add the "CPU offloading" setting (if it's not already implemented) and GGUF support when the model appears, I'm sure that the community will soon release a GGUF version of PyramidFlow.

**Comment by Kvento** [comment]
> I'm on torch 2.4.1 cu124

I have the same version, so unfortunately this is apparently not the reason.

**Comment by kijai** [comment]
> > “2080ti doesn’t support BF16, so I can only use FP16, but FP16 throws NaN errors. I tried running it with FP8, but the memory usage is outrageous. Even with 22GB of VRAM, it still runs out of memory.”
> 
> Yeah the same. If I run in fp16 I get the error "nan in latents" in the "PyramidFlow Sampler" block, and with fp8 the memory consumption is simply outrageous.
> 
> I'm not sure if "CPU offloading" is implemented in these nodes (I just couldn't find any setting with a similar name), but by analogy with CogVideoX, it could help launch the model on video cards with a smaller amount of VRAM. Although CogVideoX also didn't launch for me without "CPU offloading" enabled on the standard model. But the GGUF version launched without "CPU offloading" enabled.
> 
> I hope that @kijai will add the "CPU offloading" setting (if it's not already implemented) and GGUF support when the model appears, I'm sure that the community will soon release a GGUF version of PyramidFlow.

CPU offloading was the first thing I added, before it was in the main code, it's enabled by default and to disable it you'd have to enable the "keep_model_loaded" option. It just means moving the text encoder (and VAE) to CPU (which means RAM) after the prompt (or input image) has been encoded. Also to offload the main model before decoding so that it has all available VRAM as well.

This issue seems more about the dtype, it's an issue known in the original repo and tracked here: 

https://github.com/jy0205/Pyramid-Flow/issues/25

Currently it just doesn't seem to support fp16.

**Comment by Kvento** [comment]
Yes, I also noticed that in fp32 everything works fine, but it still doesn't fit in 11gb, damn NVIDIA, why couldn't they add another damn gigabyte to the top card of the 20 series :)

Generation starts, but the generation speed is of course terrible, apparently this is because Shared GPU Memory is used.

![2024-10-12_09-18-47](https://github.com/user-attachments/assets/dd3f3dde-4b53-46ba-8550-a80aea6945cf)

**Comment by Kvento** [comment]
Looks like I can only wait for the GGUF version :(

**Comment by LorisTecnology** [comment]
i'll test it on RTX 3060 12GB

**Comment by kijai** [comment]
miniflux should solve this in addition to the sequential_cpu_offloading
