### ISSUE TITLE
Comfy says it installed but nodes missing

### ISSUE THREAD

**Issue by TRONBFFL** [kijai/ComfyUI-PyramidFlowWrapper#14]
![Screenshot 2024-10-11 170621](https://github.com/user-attachments/assets/3b19e4fc-4f9c-4819-abce-a29c540a2df4)
PyramidFlowSampler et.all that are in the example json. 

thoughts?

**Comment by darshanvjani** [comment]
check logs, maybe you might be missing certain libraries, in the worst case try pip install -r requirements.txt from models/ComfyUI-PyramidFlowWrapper dir

**Comment by kijai** [comment]
Whenever you get nodes failed to load -errors like that, there is something in the startup log that indicates what exactly failed to load, usually something along the lines of "Module not found". Without this information we can only guess, it's most likely missing dependency and requirements.txt needs to be installed.

**Comment by Kvento** [comment]
I encountered the same problem on pure ComfyUI.
It seems that these nodes do not work without the "CogVideoX Wrepper" nodes, because as soon as I installed them, everything worked.

**Comment by TRONBFFL** [comment]
Hi all - thanks for the quick reply. I usually look for the Module not found - but I am not getting that error. 
ran the pip install requirements and it ran just fine. 
@Kvento  I installed CogVideoX successfully, but no help for me. 
I see PyramidFlow on my node list in the UI, but its showing a different node than what it is asking for. 
I'm on Windows, is there maybe a config file somewhere pointing to a linux style filepath that maybe I need to change?

![Screenshot 2024-10-12 101956](https://github.com/user-attachments/assets/f131d719-9042-46cc-9c0d-eb8c27b9bd4d)

**Comment by TRONBFFL** [comment]
@darshanvjani  should the directory be in models/ComfyUI-PyramidFlowWrapper  or  custom_nodes/ComfyUI-PyramidFlowWrapper ?  also when I installed from the Comfyui manager, it placed the node in this directory. 
![Screenshot 2024-10-12 103824](https://github.com/user-attachments/assets/670a1fce-72d6-4d36-98ba-5c3a6169feda)

**Comment by TRONBFFL** [comment]
UPDATE - 
So I deleted the directory that ComfyUI used to install from the Manager, and then instead I used git clone of this repository, then it loaded without errors - so I guess if you install use git clone and do not install from the ComfyUI manager at this time.

**Comment by kijai** [comment]
> UPDATE - So I deleted the directory that ComfyUI used to install from the Manager, and then instead I used git clone of this repository, then it loaded without errors - so I guess if you install use git clone and do not install from the ComfyUI manager at this time.

These nodes aren't in the manager yet, what you initially installed is someone else's nodes.
