### ISSUE TITLE
Is there support to run multiple prompts in a single batch?

### ISSUE THREAD

**Issue by darshanvjani** [kijai/ComfyUI-PyramidFlowWrapper#16]
The VRAM utilization for bf16 is around 12 GB. I think it will be a great idea if there is a way to utilize (lets say 24gb of 4090 GPU) the remaining 12 GB to fit it up by passing batch of size 2 instead of single prompt. Would love to know if there is any support for it?

**Comment by kijai** [comment]
Well I just tried this and sending batch to the model does work, but it doesn't use any more memory. It took 6 minutes 38 seconds to sample batch size of 2 at 1280x768, temp 16.

**Comment by kijai** [comment]
Added the support anyway, you can now chain the prompt encode nodes. I don't know if there's any speed benefit yet, but it can be convenient.
