### ISSUE TITLE
I seem to only be running the sampling at 6.4-7gb of GPU usage. Is this normal?

### ISSUE THREAD

**Issue by lijackcoder** [kijai/ComfyUI-PyramidFlowWrapper#2]
I read that it takes 10-12, I did not change any settings. I have 16gb of vram.

**Comment by kijai** [comment]
Depends on resolution, it's pretty low during sampling even at 1280x768 though, with fp8 it's around 9GB. Fp8 does affect the quality quite a bit and thus isn't recommended if not necessary.

**Comment by lijackcoder** [comment]
Alright. I mean, I am not complaining, it's working fine for me!
