### ISSUE TITLE
Dependency problems in Linux

### ISSUE THREAD

**Issue by AnilKoeroglu** [kijai/ComfyUI-PyramidFlowWrapper#23]
I am getting the following error and cannot solve it by using latest versions:

ERROR: Could not find a version that satisfies the requirement torch==2.1.2 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1)
ERROR: No matching distribution found for torch==2.1.2

**Comment by kijai** [comment]
You aren't using my nodes then, I do have torch in requirements and it's absolutely not necessary to use 2.1.2 with my nodes, 2.4.1 works fine.

**Comment by AnilKoeroglu** [comment]
I am really not sure about why it required specifically 2.1.2 but I am pretty sure it is your node. But it is solved by downgrading from python 3.12 to 3.10

**Comment by kijai** [comment]
> I am really not sure about why it required specifically 2.1.2 but I am pretty sure it is your node. But it is solved by downgrading from python 3.12 to 3.10

And I'm 100% sure it is not.

**Comment by kijai** [comment]
Just to be clear, the main original repository does have that torch version as requirement, but these nodes do not need the original repository installed nor it's dependencies.

**Comment by AnilKoeroglu** [comment]
Okay I guess I found the reason, probably it was also trying to install the dependencies of the Pyramid Flow. Sorry for the confusion
![Screenshot 2024-10-13 204838](https://github.com/user-attachments/assets/c45a75e8-4cc3-48c4-9b39-78371849aab5)

**Comment by kijai** [comment]
Okay, understood, no worries, I just don't want anyone to downgrade as I always make sure anything I do runs in current latest torch.
