### ISSUE TITLE
Model handling with human figures

### ISSUE THREAD

**Issue by ShmuelRonen** [kijai/ComfyUI-PyramidFlowWrapper#27]
Thanks for bringing PyramidFlow to ComfyUI

In all the attempts I made to animate landscapes and nature, the results turned out excellent. But as far as humans are concerned, most results create distorted movements. Is it possible to improve it?

**Comment by darshanvjani** [comment]
facing the same issue

**Comment by kijai** [comment]
https://github.com/jy0205/Pyramid-Flow

![image](https://github.com/user-attachments/assets/59d3cc7e-bf67-4878-8475-8fe005d9c646)

**Comment by ShmuelRonen** [comment]
CogVideo-Tora is much better
