### ISSUE TITLE
Expected parameter covariance_matrix (Tensor of shape (4, 4)) of distribution MultivariateNormal(loc: torch.Size([4]),

### ISSUE THREAD

**Issue by TingTingin** [kijai/ComfyUI-PyramidFlowWrapper#3]
i'm getting this error in comfy not sure what to change

`Expected parameter covariance_matrix (Tensor of shape (4, 4)) of distribution MultivariateNormal(loc: torch.Size([4]), covariance_matrix: torch.Size([4, 4])) to satisfy the constraint PositiveDefinite(), but found invalid values:
tensor([[ 1.0000, -0.3333, -0.3333, -0.3333],
[-0.3333, 1.0000, -0.3333, -0.3333],
[-0.3333, -0.3333, 1.0000, -0.3333],
[-0.3333, -0.3333, -0.3333, 1.0000]])`

![opera_qz5hXqMjRh](https://github.com/user-attachments/assets/adf5b19c-3043-438c-8d12-4b3e189265aa)

**Comment by ClintHardwood** [comment]
I'm getting the same issue.

**Comment by SamuelRobertBond** [comment]
I was getting the same issue and looked into it a bit. It looks like it was broken [here](https://github.com/kijai/ComfyUI-PyramidFlowWrapper/commit/8c18421294f433d75b40210e46088c4877329f2e#diff-c17dec839071665df4bc6e2a832bed489720c8c9d9cb9c0d2b22dcb32eaadd63L191-R183). I don't know enough about this to submit a fix, but swapping the second arg back to the previous formula fixed the issue for me.

**Comment by SamuelRobertBond** [comment]
If you looking for a fix right now you can checkout the pr above, although I'm sure a better fix is on the way.

**Comment by SamuelRobertBond** [comment]
I'm using windows 10 and most recent cuda / torch versions. I tried with multiple other versions as well.

**Comment by SamuelRobertBond** [comment]
Just in case you need the full stack
`!!! Exception during processing !!! Expected parameter covariance_matrix (Tensor of shape (4, 4)) of distribution MultivariateNormal(loc: torch.Size([4]), covariance_matrix: torch.Size([4, 4])) to satisfy the constraint PositiveDefinite(), but found invalid values:
tensor([[ 1.0000, -0.3333, -0.3333, -0.3333],
        [-0.3333,  1.0000, -0.3333, -0.3333],
        [-0.3333, -0.3333,  1.0000, -0.3333],
        [-0.3333, -0.3333, -0.3333,  1.0000]])
Traceback (most recent call last):
  File "C:\AI\ImageAI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ImageAI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ImageAI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\AI\ImageAI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ImageAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\nodes.py", line 201, in sample
    latents = model["model"].generate(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ImageAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ImageAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 585, in generate
    intermed_latents = self.generate_one_unit(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ImageAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ImageAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 248, in generate_one_unit
    noise = self.sample_block_noise(bs, ch, temp, height, width)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ImageAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 195, in sample_block_noise
    dist = torch.distributions.multivariate_normal.MultivariateNormal(torch.zeros(4), torch.eye(4) * (1 + gamma) - torch.ones(4, 4) * gamma)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ImageAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\distributions\multivariate_normal.py", line 178, in __init__
    super().__init__(batch_shape, event_shape, validate_args=validate_args)
  File "C:\AI\ImageAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\distributions\distribution.py", line 70, in __init__
    raise ValueError(
ValueError: Expected parameter covariance_matrix (Tensor of shape (4, 4)) of distribution MultivariateNormal(loc: torch.Size([4]), covariance_matrix: torch.Size([4, 4])) to satisfy the constraint PositiveDefinite(), but found invalid values:
tensor([[ 1.0000, -0.3333, -0.3333, -0.3333],
        [-0.3333,  1.0000, -0.3333, -0.3333],
        [-0.3333, -0.3333,  1.0000, -0.3333],
        [-0.3333, -0.3333, -0.3333,  1.0000]])`

**Comment by SamuelRobertBond** [comment]
Here's another odd thing, when I output the matrix to check the value it outputs the exact same thing.

Change in Code to get output
![image](https://github.com/user-attachments/assets/b5b5e249-3421-48b9-8778-5016b8093403)

Result
![image](https://github.com/user-attachments/assets/9cd20969-f9d1-42da-9291-38d8b96125c2)

**Comment by SamuelRobertBond** [comment]
I was able to get some more info by setting validation args to false
![image](https://github.com/user-attachments/assets/d70e79ce-04c3-4b83-a679-72e41d2292ca)

**Comment by kijai** [comment]
Yeah I was also looking at the matrix and don't really understand the issue. When the gamma is 1/3 it causes the error, if I use just something like 0.333 it works. I suppose adding the epsilon is still better fix.

**Comment by SamuelRobertBond** [comment]
It at least gets it working. I can pull torch on WSL and see if there is a difference in the torch distribution. It could just be a difference with how the OS handles floating point precision. I'll keep poking at it but im out of my depth when it comes to how this all works.

**Comment by SamuelRobertBond** [comment]
I changed the print options to have higher precision to get a better output for the matrices and this is what I got. Not sure what you are seeing on linux so hopefully this might be helpful.

Without epsilon
```
tensor([[ 1.0000000000, -0.3333333433, -0.3333333433, -0.3333333433],
[-0.3333333433, 1.0000000000, -0.3333333433, -0.3333333433],
[-0.3333333433, -0.3333333433, 1.0000000000, -0.3333333433],
[-0.3333333433, -0.3333333433, -0.3333333433, 1.0000000000]])
```

With epsilon
```
tensor([[ 1.0000100136, -0.3333333433, -0.3333333433, -0.3333333433],
[-0.3333333433, 1.0000100136, -0.3333333433, -0.3333333433],
[-0.3333333433, -0.3333333433, 1.0000100136, -0.3333333433],
[-0.3333333433, -0.3333333433, -0.3333333433, 1.0000100136]])
```

**Comment by SamuelRobertBond** [comment]
Another option could be limiting the amount of decimal places for the gamma. That seems to be working for me.

**Comment by kijai** [comment]
> Another option could be limiting the amount of decimal places for the gamma. That seems to be working for me.

Exactly what I did as well now, just rounding it seems to work.

**Comment by SamuelRobertBond** [comment]
It's working on my end, so it seems to have fixed the issue
