### ISSUE TITLE
Can you add support to sequential cpu offload?

### ISSUE THREAD

**Issue by Kvento** [kijai/ComfyUI-PyramidFlowWrapper#31]
Please can you add support to "sequential cpu offload" like in the original rep?
[https://github.com/jy0205/Pyramid-Flow/pull/75](https://github.com/jy0205/Pyramid-Flow/pull/75)

I tested this in their Gradio interface and it does indeed allow me to successfully generate videos on my RTX 2080ti. Of course, the generation is a little slower, but it still happens successfully.

**Comment by kijai** [comment]
I mean sure... I just never understood how anyone has patience for using that, when these things are so hit and miss with the outputs in the first place.

Anyway the new miniflux model runs with 7GB even without cpu offloading, both are added now.
