### ISSUE TITLE
Error: PyramidFlowVAELoader: module 'folder_paths' has no attribute 'get_full_path_or_raise'

### ISSUE THREAD

**Issue by Flamedragonz** [kijai/ComfyUI-PyramidFlowWrapper#40]
Please help me solve the problem. 
I select a workflow from the examples folder, enter my prompt, press the **Queue** button, and the **PyramidFlowVAELoader** node displays this error.

got prompt
!!! Exception during processing !!! module 'folder_paths' has no attribute 'get_full_path_or_raise'
Traceback (most recent call last):
  File "F:\AITOOLS\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AITOOLS\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AITOOLS\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\AITOOLS\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AITOOLS\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\nodes.py", line 92, in loadmodel
    vae_path = folder_paths.get_full_path_or_raise("vae", vae)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'folder_paths' has no attribute 'get_full_path_or_raise'

![image](https://github.com/user-attachments/assets/b29d452e-fe2e-4bea-8e97-1c5b38adf7fc)

**Comment by kijai** [comment]
Update ComfyUI itself.

**Comment by Flamedragonz** [comment]
> Update ComfyUI itself.

Thanks, it worked! It's weird that I forgot about this step!
