### ISSUE TITLE
PyramidFlowVAEEncode 54 Required input is missing: overlap_factor

### ISSUE THREAD

**Issue by TRONBFFL** [kijai/ComfyUI-PyramidFlowWrapper#52]
Not sure what I am missing here, help appreciated!  
<img width="605" alt="image" src="https://github.com/user-attachments/assets/c66fc246-dc8c-4f4f-b98b-a3b4333b0a31">

**Comment by kijai** [comment]
Remake the node, it has new widget to set tiling overlap, old workflows won't show it
