### ISSUE TITLE
Code Looking for .bin Filetype, but Huggingface has .safetensors File

### ISSUE THREAD

**Issue by camoody1** [kijai/ComfyUI-PyramidFlowWrapper#8]
`OSError: Unable to load weights from checkpoint file for 'H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\pyramidflow\pyramid-flow-sd3\diffusion_transformer_768p\diffusion_pytorch_model.bin' at 'H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\pyramidflow\pyramid-flow-sd3\diffusion_transformer_768p\diffusion_pytorch_model.bin'.`

The only filetype available on Huggingface for this file is a .safetensors filetype.

**Comment by kijai** [comment]
That's just diffusers default error, it's not looking for .bin, the .safetensors work fine. Check that you have the .json config files with correct name in that folder, it should just be `config.json`

**Comment by camoody1** [comment]
I found my issue. It was an ID10T error. My apologies.
