### ISSUE TITLE
Image input?

### ISSUE THREAD

**Issue by festivus37** [kijai/ComfyUI-PyramidFlowWrapper#9]
Hi, thanks for this. One question, what's the right way to have an input image. I see the incoming latent connector, and I see the pyramidflow vae encoder node, but what should I be connecting to the model node there? Is there a pyramid node vae model loader I'm missing? Thanks again.

**Comment by kijai** [comment]
> Hi, thanks for this. One question, what's the right way to have an input image. I see the incoming latent connector, and I see the pyramidflow vae encoder node, but what should I be connecting to the model node there? Is there a pyramid node vae model loader I'm missing? Thanks again.

The VAE is in the model along with the text encoder for now, might separate them later. There's example workflow for image2vid in the examples -folder too.

**Comment by festivus37** [comment]
Thanks so much. Just pasting an image here in case anyone else sees this post.

![image](https://github.com/user-attachments/assets/e1cc1cf7-4bac-44c8-81d2-58f4b1177454)
